[app]
port = 3000
debug = true
max_file_size = 10
phase = "register"
event_day = 1
e_stamp_count = 4
redeem_full = false

[service]
backend = "localhost:3001"
auth = "localhost:3002"
file = "localhost:3003"
checkin = "localhost:3004"